### ISSUE TITLE
First Wednesday of term is not correct

### ISSUE THREAD

**Issue by benjamin-antupit** [Akalay27/workday-schedule-exporter#5]
I love this tool! Thanks for making it. 

One feature request: it would be great if we could check a box (or automatically) override the first Wednesday of the term with a Monday schedule.

**Comment by Akalay27** [comment]
Fixed in https://github.com/Akalay27/workday-schedule-exporter/commit/97ca5967d969810f43454cb0a21673f09514795d. Thanks! Now also fixes the 3 special schedule days in the year.
